// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

// ApiError defines model for api-error.
type ApiError struct {
	Message string `json:"message"`
}

// Operation defines model for operation.
type Operation struct {
	A float32 `json:"a"`
	B float32 `json:"b"`
}

// Result defines model for result.
type Result struct {
	Result float32 `json:"result"`
}

// A defines model for a.
type A = float32

// B defines model for b.
type B = float32

// AddParams defines parameters for Add.
type AddParams struct {
	A Operation `form:"a" json:"a"`
}

// DivideParams defines parameters for Divide.
type DivideParams struct {
	A A `form:"a" json:"a"`
	B B `form:"b" json:"b"`
}

// MultiplyParams defines parameters for Multiply.
type MultiplyParams struct {
	A A `form:"a" json:"a"`
	B B `form:"b" json:"b"`
}

// SubtractParams defines parameters for Subtract.
type SubtractParams struct {
	A A `form:"a" json:"a"`
	B B `form:"b" json:"b"`
}
