openapi: 3.0.3
info:
  title: Math API
  version: 0.1.0

paths:
  /add:
    get:
      operationId: add
      parameters:
        - $ref: "./parameters/a.yaml"
        - $ref: "./parameters/b.yaml"
      responses:
        "200":
          $ref: "#/components/responses/Result"
        "400":
          $ref: "#/components/responses/APIError"

  /subtract:
    get:
      operationId: subtract
      parameters:
        - $ref: "./parameters/a.yaml"
        - $ref: "./parameters/b.yaml"
      responses:
        "200":
          $ref: "#/components/responses/Result"
        "400":
          $ref: "#/components/responses/APIError"

  /multiply:
    get:
      operationId: multiply
      parameters:
        - $ref: "./parameters/a.yaml"
        - $ref: "./parameters/b.yaml"
      responses:
        "200":
          $ref: "#/components/responses/Result"
        "400":
          $ref: "#/components/responses/APIError"

  /divide:
    get:
      operationId: divide
      parameters:
        - $ref: "./parameters/a.yaml"
        - $ref: "./parameters/b.yaml"
      responses:
        "200":
          $ref: "#/components/responses/Result"
        "400":
          $ref: "#/components/responses/APIError"

components:
  schemas:
    Operation:
      $ref: "./schemas/operation.yaml"
    Result:
      $ref: "./schemas/result.yaml"
    APIError:
      $ref: "./schemas/api-error.yaml"

  responses:
    Result:
      $ref: "./responses/result.yaml"
    APIError:
      $ref: "./responses/api-error.yaml"