openapi: 3.0.3
info:
  title: Math API
  version: 0.1.0

paths:
  /subtract:
    get:
      operationId: subtract
      parameters:
        - $ref: "./a.yaml"
        - $ref: "./b.yaml"
      responses:
        "200":
          $ref: "./200.yaml"
        "400":
          $ref: "./400.yaml"
  /add:
    get:
      operationId: add
      parameters:
        - $ref: "./a.yaml"
        - $ref: "./b.yaml"
      responses:
        "200":
          $ref: "./200.yaml"
        "400":
          $ref: "./400.yaml"
  /multiply:
    get:
      operationId: multiply
      parameters:
        - $ref: "./a.yaml"
        - $ref: "./b.yaml"
      responses:
        "200":
          $ref: "./200.yaml"
        "400":
          $ref: "./400.yaml"
  /divide:
    get:
      operationId: divide
      parameters:
        - $ref: "./a.yaml"
        - $ref: "./b.yaml"
      responses:
        "200":
          $ref: "./200.yaml"
        "400":
          $ref: "./400.yaml"

components:
  schemas:
    Operation:
      type: object
      properties: 
        a:
          type: number
        b:
          type: number
      required: [a, b]
